### ISSUE TITLE
part04-e16_split_date; submit: ImportError: No module named 'pandas' 

### ISSUE THREAD

**Issue by kotalbert** [jttoivon/data-analysis-with-python-spring-2019#5]
I'm under Windows, until now submits were successful.

```
>tmc test part04-e16_split_date
Testing: part04-e16_split_date
Test results: 5/5 tests passed
100%
All tests passed! Submit to server with 'tmc submit'

>tmc submit part04-e16_split_date
Submitting: part04-e16_split_date
Failed: unittest.loader._FailedTest.test.test_split_date
        Failed to import test module: test.test_split_date
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/tmc/test/test_split_date.py", line 6, in <module>
    import pandas as pd
ImportError: No module named 'pandas'


Test results: 0/1 tests passed
  0%

**Comment by kotalbert** [comment]
Working again
```
Submitting: part04-e16_split_date
Test results: 5/5 tests passed
100%
All tests passed on server!
Points permanently awarded: [p04-16.1]
Model solution: https://tmc.mooc.fi/exercises/67033/solution
